// 
// AUTOGENERATED FILE
// DO NOT EDIT
//
let app = require('./infinite-horisontal-list');
module.hot && module.hot.accept('./infinite-horisontal-list', app.main);
if(require.main === module) app.main();
